import type { DiscreteTheme, InspirationFingerprint, InspirationTarget, ThemeTokens } from './types';

type ThemeSeed = {
  id: string;
  name: string;
  blurb: string;
  swatches: [string, string];
  palette: Pick<ThemeTokens, 'background' | 'surface' | 'surface2' | 'text' | 'muted' | 'border' | 'accent' | 'accent2' | 'heroGradientA' | 'heroGradientB'>;
  sizing: Omit<ThemeTokens, keyof ThemeSeed['palette']>;
  discrete: DiscreteTheme;
  fingerprint: InspirationFingerprint;
};

const positionFromFingerprint = (fingerprint: InspirationFingerprint) => ({
  x: Math.min(0.94, Math.max(0.06, 0.5 + (fingerprint.product - fingerprint.editorial) * 0.26 + (fingerprint.precision - 0.5) * 0.08)),
  y: Math.min(0.94, Math.max(0.06, 0.5 + (fingerprint.energy - fingerprint.warmth) * 0.24 + (fingerprint.density - 0.5) * 0.12)),
});

const makeTheme = (seed: ThemeSeed): InspirationTarget => ({
  id: seed.id,
  name: seed.name,
  blurb: seed.blurb,
  swatches: seed.swatches,
  discrete: seed.discrete,
  fingerprint: seed.fingerprint,
  position: positionFromFingerprint(seed.fingerprint),
  tokens: {
    ...seed.palette,
    ...seed.sizing,
  },
});

const sizing = (
  heroSize: number,
  titleSize: number,
  bodySize: number,
  radius: number,
  pageWidth: number,
  gap: number,
  discrete: DiscreteTheme,
): Omit<ThemeTokens, 'background' | 'surface' | 'surface2' | 'text' | 'muted' | 'border' | 'accent' | 'accent2' | 'heroGradientA' | 'heroGradientB'> => ({
  heroSize,
  titleSize,
  bodySize,
  heroWeight: discrete.fontFamily === 'serif' ? 740 : discrete.fontFamily === 'mono' ? 710 : 690,
  titleWeight: 650,
  bodyWeight: 430,
  tracking: discrete.fontFamily === 'mono' ? 0.07 : discrete.fontFamily === 'serif' ? 0.03 : 0.014,
  radius,
  borderWidth: 1,
  shadowY: discrete.density === 'dense' ? 2 : 5,
  shadowBlur: discrete.density === 'dense' ? 8 : 16,
  shadowAlpha: discrete.fontFamily === 'mono' ? 0.14 : 0.05,
  pageWidth,
  gap,
  pad: gap + 4,
  cardPad: gap - 2,
  lineHeight: discrete.fontFamily === 'serif' ? 1.58 : 1.52,
});

const seeds: ThemeSeed[] = [
  {
    id: 'acid-editorial',
    name: 'Acid Editorial',
    blurb: 'Poster-sized serif and sour green tension.',
    swatches: ['#F3FF74', '#3D8D3A'],
    palette: { background: '#F7F8EE', surface: '#FFFFFF', surface2: '#EDF4D8', text: '#172114', muted: '#5E6959', border: '#8CA76B', accent: '#2E7D32', accent2: '#D5E652', heroGradientA: '#F6F39B', heroGradientB: '#DFEFB5' },
    discrete: { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'solid', density: 'airy' },
    sizing: sizing(74, 30, 17, 18, 1160, 24, { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'solid', density: 'airy' }),
    fingerprint: { editorial: 0.92, product: 0.16, warmth: 0.6, energy: 0.88, precision: 0.38, density: 0.26 },
  },
  {
    id: 'paper-column',
    name: 'Paper Column',
    blurb: 'Cream stock, restrained serif, Sunday review calm.',
    swatches: ['#F2EBDD', '#B88D55'],
    palette: { background: '#F8F3E9', surface: '#FFFDF9', surface2: '#F1E7D5', text: '#2B2117', muted: '#73614C', border: '#D6C4AA', accent: '#7E5C32', accent2: '#B8894B', heroGradientA: '#F6EAD5', heroGradientB: '#E8D9BE' },
    discrete: { fontFamily: 'serif', heroCase: 'title', buttonStyle: 'outline', density: 'balanced' },
    sizing: sizing(66, 29, 17, 14, 1120, 22, { fontFamily: 'serif', heroCase: 'title', buttonStyle: 'outline', density: 'balanced' }),
    fingerprint: { editorial: 0.84, product: 0.18, warmth: 0.72, energy: 0.28, precision: 0.42, density: 0.44 },
  },
  {
    id: 'museum-label',
    name: 'Museum Label',
    blurb: 'Quiet labels, warm paper, object-first framing.',
    swatches: ['#F0E5D8', '#64706A'],
    palette: { background: '#F5EFE5', surface: '#FBF8F3', surface2: '#EEE4D8', text: '#26201A', muted: '#6C6257', border: '#D8CAB9', accent: '#55635D', accent2: '#A08D72', heroGradientA: '#EFE6D8', heroGradientB: '#E2D6C6' },
    discrete: { fontFamily: 'serif', heroCase: 'sentence', buttonStyle: 'outline', density: 'balanced' },
    sizing: sizing(60, 27, 16, 12, 1100, 20, { fontFamily: 'serif', heroCase: 'sentence', buttonStyle: 'outline', density: 'balanced' }),
    fingerprint: { editorial: 0.72, product: 0.24, warmth: 0.64, energy: 0.22, precision: 0.56, density: 0.45 },
  },
  {
    id: 'ink-study',
    name: 'Ink Study',
    blurb: 'Blue-black ink with deliberate proportion shifts.',
    swatches: ['#D7DCEB', '#1E263D'],
    palette: { background: '#EEF1F6', surface: '#FFFFFF', surface2: '#E1E7F0', text: '#141B2A', muted: '#5C6780', border: '#C8D0E1', accent: '#22304D', accent2: '#7686AB', heroGradientA: '#E0E6F1', heroGradientB: '#CDD8E6' },
    discrete: { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'solid', density: 'airy' },
    sizing: sizing(68, 28, 16, 12, 1180, 24, { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'solid', density: 'airy' }),
    fingerprint: { editorial: 0.78, product: 0.32, warmth: 0.28, energy: 0.36, precision: 0.74, density: 0.32 },
  },
  {
    id: 'soft-saas',
    name: 'Soft SaaS',
    blurb: 'Rounded product chrome with beige restraint.',
    swatches: ['#F4ECE3', '#A98765'],
    palette: { background: '#F6F1EA', surface: '#FEFCFA', surface2: '#EFE6DB', text: '#2F271F', muted: '#726659', border: '#D8CCBE', accent: '#A47F5F', accent2: '#E0CCBA', heroGradientA: '#F3E8DD', heroGradientB: '#E7D9CA' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' },
    sizing: sizing(54, 24, 15, 16, 1200, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' }),
    fingerprint: { editorial: 0.26, product: 0.86, warmth: 0.62, energy: 0.32, precision: 0.72, density: 0.54 },
  },
  {
    id: 'linen-panel',
    name: 'Linen Panel',
    blurb: 'Warm surfaces, quiet contrast, no hard gloss.',
    swatches: ['#F8F4ED', '#A06E46'],
    palette: { background: '#FBF6EF', surface: '#FFFFFF', surface2: '#F4EADF', text: '#30271D', muted: '#7C6D5B', border: '#DFCDB8', accent: '#8F6240', accent2: '#D6B08A', heroGradientA: '#F2E7DB', heroGradientB: '#E9D7C1' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' },
    sizing: sizing(56, 24, 15, 14, 1180, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' }),
    fingerprint: { editorial: 0.34, product: 0.74, warmth: 0.72, energy: 0.26, precision: 0.66, density: 0.5 },
  },
  {
    id: 'studio-ui',
    name: 'Studio UI',
    blurb: 'Product design tool palette with graphite structure.',
    swatches: ['#CCD5DF', '#3F556B'],
    palette: { background: '#EEF2F5', surface: '#FFFFFF', surface2: '#E3E9EE', text: '#16202A', muted: '#667686', border: '#CCD6E0', accent: '#35506A', accent2: '#91A4B8', heroGradientA: '#E4EBF1', heroGradientB: '#D7E1EB' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'solid', density: 'balanced' },
    sizing: sizing(52, 23, 15, 12, 1220, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'solid', density: 'balanced' }),
    fingerprint: { editorial: 0.22, product: 0.92, warmth: 0.22, energy: 0.34, precision: 0.9, density: 0.52 },
  },
  {
    id: 'civic-grid',
    name: 'Civic Grid',
    blurb: 'Public-service clarity with hard-working blue.',
    swatches: ['#DBE6F7', '#2F5AA8'],
    palette: { background: '#F2F6FB', surface: '#FFFFFF', surface2: '#E3EDF9', text: '#17253D', muted: '#5C7090', border: '#C9D8EE', accent: '#2E5CA6', accent2: '#8DA9D8', heroGradientA: '#E2EBF8', heroGradientB: '#D5E2F4' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'dense' },
    sizing: sizing(58, 25, 15, 10, 1200, 20, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'dense' }),
    fingerprint: { editorial: 0.18, product: 0.82, warmth: 0.18, energy: 0.44, precision: 0.88, density: 0.7 },
  },
  {
    id: 'warm-night',
    name: 'Warm Night',
    blurb: 'Magazine darkness with ember edges.',
    swatches: ['#F08A4B', '#261411'],
    palette: { background: '#151111', surface: '#201918', surface2: '#2D221F', text: '#F2E7DB', muted: '#B69C8A', border: '#644334', accent: '#E68043', accent2: '#8A4D2C', heroGradientA: '#311B16', heroGradientB: '#1B1312' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'outline', density: 'dense' },
    sizing: sizing(60, 26, 15, 12, 1040, 18, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'outline', density: 'dense' }),
    fingerprint: { editorial: 0.62, product: 0.28, warmth: 0.9, energy: 0.56, precision: 0.44, density: 0.74 },
  },
  {
    id: 'ember-ledger',
    name: 'Ember Ledger',
    blurb: 'Dark finance paneling with paper-like rhythm.',
    swatches: ['#D7A06A', '#2D1C14'],
    palette: { background: '#171110', surface: '#241A17', surface2: '#30221E', text: '#F1E6D9', muted: '#B49B88', border: '#694A3A', accent: '#D58E51', accent2: '#8B5A36', heroGradientA: '#38231B', heroGradientB: '#1B1412' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'outline', density: 'dense' },
    sizing: sizing(56, 24, 15, 10, 1060, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'outline', density: 'dense' }),
    fingerprint: { editorial: 0.42, product: 0.48, warmth: 0.84, energy: 0.42, precision: 0.68, density: 0.72 },
  },
  {
    id: 'charcoal-brief',
    name: 'Charcoal Brief',
    blurb: 'Muted report styling with a burnt red accent.',
    swatches: ['#CBB4A5', '#23201F'],
    palette: { background: '#181616', surface: '#222020', surface2: '#2B2828', text: '#F0E8E4', muted: '#B3A59D', border: '#5D514C', accent: '#B96E52', accent2: '#7A5A4A', heroGradientA: '#2A2322', heroGradientB: '#1C1818' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'dense' },
    sizing: sizing(54, 24, 15, 10, 1040, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'dense' }),
    fingerprint: { editorial: 0.38, product: 0.56, warmth: 0.68, energy: 0.2, precision: 0.74, density: 0.8 },
  },
  {
    id: 'forest-terminal',
    name: 'Forest Terminal',
    blurb: 'Deep green console with measured mono density.',
    swatches: ['#64D2A5', '#0E1A17'],
    palette: { background: '#0D1614', surface: '#15211D', surface2: '#1B2A25', text: '#E4F5EC', muted: '#9CB9AA', border: '#365046', accent: '#58C595', accent2: '#95E2BF', heroGradientA: '#143025', heroGradientB: '#0E1715' },
    discrete: { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'outline', density: 'dense' },
    sizing: sizing(48, 22, 14, 10, 1120, 18, { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'outline', density: 'dense' }),
    fingerprint: { editorial: 0.16, product: 0.7, warmth: 0.28, energy: 0.58, precision: 0.88, density: 0.86 },
  },
  {
    id: 'neon-console',
    name: 'Neon Console',
    blurb: 'Violet console with electric secondary accents.',
    swatches: ['#8F7CFF', '#121529'],
    palette: { background: '#0E1222', surface: '#171C33', surface2: '#202847', text: '#EEF0FF', muted: '#A6ADD8', border: '#364173', accent: '#8F7CFF', accent2: '#58D5FF', heroGradientA: '#1F2755', heroGradientB: '#0E1224' },
    discrete: { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'solid', density: 'balanced' },
    sizing: sizing(50, 22, 14, 12, 1120, 18, { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'solid', density: 'balanced' }),
    fingerprint: { editorial: 0.24, product: 0.76, warmth: 0.12, energy: 0.82, precision: 0.82, density: 0.62 },
  },
  {
    id: 'signal-lab',
    name: 'Signal Lab',
    blurb: 'Dark scientific console with amber instrumentation.',
    swatches: ['#F2B862', '#111821'],
    palette: { background: '#11161B', surface: '#181F27', surface2: '#222B33', text: '#EBEFF1', muted: '#9EA8AE', border: '#3A4852', accent: '#E6A44B', accent2: '#6EC5FF', heroGradientA: '#1E252B', heroGradientB: '#10151A' },
    discrete: { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'outline', density: 'dense' },
    sizing: sizing(48, 22, 14, 10, 1120, 18, { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'outline', density: 'dense' }),
    fingerprint: { editorial: 0.18, product: 0.8, warmth: 0.36, energy: 0.68, precision: 0.9, density: 0.82 },
  },
  {
    id: 'terminal-slate',
    name: 'Terminal Slate',
    blurb: 'Cyan-on-slate machine room without the glow soup.',
    swatches: ['#69D4E6', '#11161B'],
    palette: { background: '#0F1418', surface: '#171D22', surface2: '#212930', text: '#E7F1F3', muted: '#A6B7BA', border: '#3B4952', accent: '#61CFE0', accent2: '#93E4F0', heroGradientA: '#172329', heroGradientB: '#101418' },
    discrete: { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'tint', density: 'dense' },
    sizing: sizing(47, 22, 14, 10, 1100, 18, { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'tint', density: 'dense' }),
    fingerprint: { editorial: 0.14, product: 0.74, warmth: 0.08, energy: 0.56, precision: 0.86, density: 0.84 },
  },
  {
    id: 'citrus-sheet',
    name: 'Citrus Sheet',
    blurb: 'Lightweight planning surface with citrus markers.',
    swatches: ['#F7F6CF', '#4E8E56'],
    palette: { background: '#FAF9EF', surface: '#FFFFFF', surface2: '#F2F1D9', text: '#1D2518', muted: '#616B57', border: '#D9D7B3', accent: '#4C8753', accent2: '#E4DD5C', heroGradientA: '#F6F0B9', heroGradientB: '#E5F2C5' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'airy' },
    sizing: sizing(62, 27, 16, 12, 1180, 20, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'airy' }),
    fingerprint: { editorial: 0.44, product: 0.6, warmth: 0.74, energy: 0.62, precision: 0.52, density: 0.28 },
  },
  {
    id: 'sunset-brochure',
    name: 'Sunset Brochure',
    blurb: 'Orange brochure energy with balanced product spacing.',
    swatches: ['#FFD2A4', '#C45A37'],
    palette: { background: '#FFF3E7', surface: '#FFFFFF', surface2: '#F8E2CF', text: '#382316', muted: '#88634D', border: '#E8C6AA', accent: '#C36037', accent2: '#E8A164', heroGradientA: '#FFD8B1', heroGradientB: '#F1C89F' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'balanced' },
    sizing: sizing(58, 25, 15, 14, 1200, 18, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'balanced' }),
    fingerprint: { editorial: 0.46, product: 0.58, warmth: 0.88, energy: 0.74, precision: 0.48, density: 0.42 },
  },
  {
    id: 'harbor-signal',
    name: 'Harbor Signal',
    blurb: 'Marine blue structure with orange navigation cues.',
    swatches: ['#B2D6F0', '#2A567A'],
    palette: { background: '#F0F6FB', surface: '#FFFFFF', surface2: '#E2EDF6', text: '#17304A', muted: '#607A90', border: '#C5D9E8', accent: '#285678', accent2: '#EA9453', heroGradientA: '#DBEAF6', heroGradientB: '#D1E1EF' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'tint', density: 'balanced' },
    sizing: sizing(57, 25, 15, 12, 1200, 18, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'tint', density: 'balanced' }),
    fingerprint: { editorial: 0.26, product: 0.74, warmth: 0.32, energy: 0.58, precision: 0.8, density: 0.52 },
  },
  {
    id: 'dusty-index',
    name: 'Dusty Index',
    blurb: 'Muted mauve system for archive-style interfaces.',
    swatches: ['#E5D6DC', '#6A4D58'],
    palette: { background: '#F7F0F3', surface: '#FFFFFF', surface2: '#EFDDE3', text: '#2F1E26', muted: '#7A6470', border: '#DDC5CE', accent: '#694E59', accent2: '#B98C99', heroGradientA: '#F0DCE3', heroGradientB: '#E7D2D9' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'outline', density: 'balanced' },
    sizing: sizing(58, 25, 15, 12, 1160, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'outline', density: 'balanced' }),
    fingerprint: { editorial: 0.56, product: 0.44, warmth: 0.58, energy: 0.24, precision: 0.62, density: 0.46 },
  },
  {
    id: 'alpine-ledger',
    name: 'Alpine Ledger',
    blurb: 'Cold mint ledger with crisp, low-noise spacing.',
    swatches: ['#D9F0EA', '#3B6861'],
    palette: { background: '#F1F8F6', surface: '#FFFFFF', surface2: '#E0F0EB', text: '#17312D', muted: '#5E7B77', border: '#C5E1DA', accent: '#3B6861', accent2: '#8AB7AD', heroGradientA: '#D7ECE5', heroGradientB: '#CEE5DE' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'solid', density: 'balanced' },
    sizing: sizing(55, 24, 15, 10, 1220, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'solid', density: 'balanced' }),
    fingerprint: { editorial: 0.22, product: 0.88, warmth: 0.26, energy: 0.22, precision: 0.84, density: 0.48 },
  },
  {
    id: 'orchid-signal',
    name: 'Orchid Signal',
    blurb: 'Purple-tinted product surface with soft control accents.',
    swatches: ['#E6D7F4', '#7654A2'],
    palette: { background: '#F5F0FA', surface: '#FFFFFF', surface2: '#EBE0F5', text: '#281D3A', muted: '#6E6283', border: '#D9CBEA', accent: '#7654A2', accent2: '#B692D9', heroGradientA: '#E9DDF5', heroGradientB: '#DDD0EF' },
    discrete: { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' },
    sizing: sizing(56, 24, 15, 12, 1180, 18, { fontFamily: 'sans', heroCase: 'sentence', buttonStyle: 'tint', density: 'balanced' }),
    fingerprint: { editorial: 0.34, product: 0.72, warmth: 0.3, energy: 0.42, precision: 0.76, density: 0.5 },
  },
  {
    id: 'copper-report',
    name: 'Copper Report',
    blurb: 'Serif-heavy annual report with copper sectioning.',
    swatches: ['#EDD9C2', '#9C6542'],
    palette: { background: '#FBF4EC', surface: '#FFFFFF', surface2: '#F2E4D6', text: '#312217', muted: '#7C6552', border: '#E0C9B4', accent: '#98613F', accent2: '#D39A72', heroGradientA: '#F3E1D0', heroGradientB: '#E8D0BA' },
    discrete: { fontFamily: 'serif', heroCase: 'title', buttonStyle: 'outline', density: 'airy' },
    sizing: sizing(70, 28, 16, 12, 1140, 20, { fontFamily: 'serif', heroCase: 'title', buttonStyle: 'outline', density: 'airy' }),
    fingerprint: { editorial: 0.82, product: 0.26, warmth: 0.8, energy: 0.4, precision: 0.54, density: 0.3 },
  },
  {
    id: 'graphite-review',
    name: 'Graphite Review',
    blurb: 'Serif headlines on graphite neutrals for critical reading.',
    swatches: ['#DADBDD', '#43484F'],
    palette: { background: '#F3F4F5', surface: '#FFFFFF', surface2: '#E7EAED', text: '#20252C', muted: '#6C7681', border: '#D3D8DE', accent: '#43484F', accent2: '#8E98A4', heroGradientA: '#E9ECEF', heroGradientB: '#DCE2E8' },
    discrete: { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'outline', density: 'airy' },
    sizing: sizing(68, 28, 16, 10, 1160, 20, { fontFamily: 'serif', heroCase: 'upper', buttonStyle: 'outline', density: 'airy' }),
    fingerprint: { editorial: 0.78, product: 0.34, warmth: 0.12, energy: 0.18, precision: 0.72, density: 0.34 },
  },
  {
    id: 'field-notes',
    name: 'Field Notes',
    blurb: 'Olive field journal with toughened utility spacing.',
    swatches: ['#E0E0B8', '#687348'],
    palette: { background: '#F7F7EC', surface: '#FFFFFF', surface2: '#ECECCF', text: '#242716', muted: '#697052', border: '#D6D7AE', accent: '#657145', accent2: '#BDBB62', heroGradientA: '#ECECBF', heroGradientB: '#DEE6C1' },
    discrete: { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'balanced' },
    sizing: sizing(61, 26, 15, 10, 1160, 18, { fontFamily: 'sans', heroCase: 'title', buttonStyle: 'solid', density: 'balanced' }),
    fingerprint: { editorial: 0.48, product: 0.56, warmth: 0.68, energy: 0.36, precision: 0.5, density: 0.5 },
  },
  {
    id: 'night-broadcast',
    name: 'Night Broadcast',
    blurb: 'Dark broadcast desk with warm brass data markers.',
    swatches: ['#E6BE84', '#191B27'],
    palette: { background: '#11131B', surface: '#191C26', surface2: '#232736', text: '#EEF0F5', muted: '#A6ACBC', border: '#3F455A', accent: '#D6A96B', accent2: '#7698D9', heroGradientA: '#202434', heroGradientB: '#11131C' },
    discrete: { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'tint', density: 'dense' },
    sizing: sizing(52, 23, 14, 10, 1120, 18, { fontFamily: 'mono', heroCase: 'upper', buttonStyle: 'tint', density: 'dense' }),
    fingerprint: { editorial: 0.26, product: 0.78, warmth: 0.44, energy: 0.7, precision: 0.84, density: 0.82 },
  },
];

export const themeLibrary = seeds.map(makeTheme);
export const themeLibraryMap = new Map(themeLibrary.map((target) => [target.id, target]));
